export { TestRailClient } from './client.js';
export {
    TestRailApiError,
    TestRailLicenseError,
    TestRailPaginationError,
    TestRailValidationError,
    handleZodError,
} from './errors.js';
export type {
    Page,
    PageLinks,
    PaginatedRequestOptions,
    PaginationErrorReason,
    PaginationSafetyOptions,
} from './pagination.js';
export {
    DEFAULT_PAGE_SIZE,
    DEFAULT_MAX_PAGES,
    DEFAULT_MAX_ITEMS,
    DEFAULT_MAX_PAGINATION_DURATION_MS,
    DEFAULT_MAX_PAGINATION_BYTES,
    MAX_PAGINATION_LIMIT,
    MAX_PAGINATION_BYTES,
} from './constants.js';
export {
    TestRailConfigSchema,
    PaginationSchema,
    UserSchema,
    RoleSchema,
    GroupSchema,
    ProjectSchema,
    SuiteSchema,
    LabelEmbeddedSchema,
    LabelSchema,
    CaseSchema,
    SectionSchema,
    RunSchema,
    PlanEntrySchema,
    PlanSchema,
    TestSchema,
    ResultSchema,
    MilestoneSchema,
    StatusSchema,
    PrioritySchema,
    CaseStatusSchema,
    HistoryChangeSchema,
    HistoryEntrySchema,
    CaseFieldConfigSchema,
    CaseFieldSchema,
    AddCaseFieldResponseSchema,
    ResultFieldConfigSchema,
    ResultFieldSchema,
    CaseTypeSchema,
    TemplateSchema,
    ConfigurationSchema,
    ConfigurationGroupSchema,
    AttachmentSchema,
    SharedStepSchema,
    StepHistoryEntrySchema,
    VariableSchema,
    DatasetSchema,
    DatasetVariableSchema,
    ReportSchema,
    ReportResultSchema,
    AddCasePayloadSchema,
    AddCasesBulkPayloadSchema,
    UpdateCasePayloadSchema,
    UpdateCasesPayloadSchema,
    DeleteCasesPayloadSchema,
    SoftDeletePreviewSchema,
    CopyCasesToSectionPayloadSchema,
    MoveCasesToSectionPayloadSchema,
    AddCaseFieldPayloadSchema,
    AddCaseFieldConfigPayloadSchema,
    MoveSectionPayloadSchema,
    AddRunPayloadSchema,
    UpdateRunPayloadSchema,
    AddResultPayloadSchema,
    AddResultForCasePayloadSchema,
    AddResultsForCasesPayloadSchema,
    AddResultForTestPayloadSchema,
    AddResultsPayloadSchema,
    PlanEntryRunPayloadSchema,
    AddPlanEntryPayloadSchema,
    UpdatePlanEntryPayloadSchema,
    AddRunToPlanEntryPayloadSchema,
    UpdateRunInPlanEntryPayloadSchema,
    AddPlanPayloadSchema,
    UpdatePlanPayloadSchema,
    AddProjectPayloadSchema,
    UpdateProjectPayloadSchema,
    AddSuitePayloadSchema,
    UpdateSuitePayloadSchema,
    AddSectionPayloadSchema,
    UpdateSectionPayloadSchema,
    AddMilestonePayloadSchema,
    UpdateMilestonePayloadSchema,
    UpdateLabelPayloadSchema,
    UpdateTestLabelsPayloadSchema,
    UpdateTestsLabelsPayloadSchema,
    UpdateTestsResponseSchema,
    AddVariablePayloadSchema,
    UpdateVariablePayloadSchema,
    AddGroupPayloadSchema,
    UpdateGroupPayloadSchema,
    AddDatasetPayloadSchema,
    UpdateDatasetPayloadSchema,
    AddSharedStepPayloadSchema,
    UpdateSharedStepPayloadSchema,
    AddConfigurationGroupPayloadSchema,
    UpdateConfigurationGroupPayloadSchema,
    AddConfigurationPayloadSchema,
    UpdateConfigurationPayloadSchema,
    UserAddPayloadSchema,
    UserUpdatePayloadSchema,
} from './schemas.js';
export type {
    AddCasePayload,
    AddCasesBulkPayload,
    UpdateCasePayload,
    UpdateCasesPayload,
    DeleteCasesPayload,
    SoftDeletePreview,
    CopyCasesToSectionPayload,
    MoveCasesToSectionPayload,
    AddCaseFieldPayload,
    AddCaseFieldConfigPayload,
    AddCaseFieldResponse,
    MoveSectionPayload,
    AddRunPayload,
    UpdateRunPayload,
    AddResultPayload,
    AddResultForCasePayload,
    AddResultsForCasesPayload,
    AddResultForTestPayload,
    AddResultsPayload,
    PlanEntryRunPayload,
    AddPlanEntryPayload,
    UpdatePlanEntryPayload,
    AddRunToPlanEntryPayload,
    UpdateRunInPlanEntryPayload,
    AddPlanPayload,
    UpdatePlanPayload,
    AddProjectPayload,
    UpdateProjectPayload,
    AddSuitePayload,
    UpdateSuitePayload,
    AddSectionPayload,
    UpdateSectionPayload,
    AddMilestonePayload,
    UpdateMilestonePayload,
    Label,
    UpdateLabelPayload,
    UpdateTestLabelsPayload,
    UpdateTestsLabelsPayload,
    UpdateTestsResponse,
    Variable,
    AddVariablePayload,
    UpdateVariablePayload,
    Group,
    AddGroupPayload,
    UpdateGroupPayload,
    Dataset,
    DatasetVariable,
    AddDatasetPayload,
    UpdateDatasetPayload,
    SharedStep,
    StepHistoryEntry,
    AddSharedStepPayload,
    UpdateSharedStepPayload,
    AddConfigurationGroupPayload,
    UpdateConfigurationGroupPayload,
    AddConfigurationPayload,
    UpdateConfigurationPayload,
    UserAddPayload,
    UserUpdatePayload,
    LabelEmbedded,
} from './schemas.js';
export type { GetAllCasesOptions, GetAllHistoryForCaseOptions, GetHistoryForCaseOptions } from './modules/cases.js';
export type { GetAllTestsOptions } from './modules/tests.js';
export type { GetAllResultsOptions } from './modules/results.js';
export type { GetAllAttachmentsOptions, GetAttachmentsOptions } from './modules/attachments.js';
export type { GetAllRunsOptions } from './modules/runs.js';
export type { GetAllPlansOptions } from './modules/plans.js';
export type { GetAllProjectsOptions, GetProjectsPageOptions } from './modules/projects.js';
export type { GetAllSectionsOptions, GetSectionsOptions } from './modules/sections.js';
export type { GetAllMilestonesOptions } from './modules/milestones.js';
export type { GetAllSuitesOptions, GetSuitesOptions } from './modules/suites.js';
export type {
    GetAllSharedStepHistoryOptions,
    GetAllSharedStepsOptions,
    GetSharedStepHistoryOptions,
    GetSharedStepsOptions,
} from './modules/sharedSteps.js';
export type { GetAllLabelsOptions, GetLabelsOptions } from './modules/labels.js';
export type { GetAllDatasetsOptions } from './modules/datasets.js';
export type { GetAllVariablesOptions } from './modules/variables.js';
export type { GetAllCaseStatusesOptions, GetAllRolesOptions } from './modules/metadata.js';
export type { GetAllGroupsOptions } from './modules/users.js';
export type {
    TestRailConfig,
    SchemaMismatch,
    RateLimiterConfig,
    Case,
    Suite,
    Section,
    Project,
    Plan,
    PlanEntry,
    Run,
    Test,
    Result,
    Milestone,
    User,
    Status,
    Priority,
    GetCasesOptions,
    GetPlansOptions,
    GetTestsOptions,
    GetResultsOptions,
    GetMilestonesOptions,
    GetRunsOptions,
    ResultField,
    ResultFieldConfig,
    CaseField,
    CaseFieldConfig,
    CaseType,
    Template,
    ConfigurationGroup,
    Configuration,
    Role,
    Attachment,
    Report,
    ReportResult,
    HistoryEntry,
    HistoryChange,
    CaseStatus,
    SoftDeleteOptions,
    UploadFileInput,
    UploadFilePathInput,
} from './types.js';
