export { TestRailClient } from './client.js';
export { TestRailApiError, TestRailValidationError } from './errors.js';
export type {
    TestRailConfig,
    TestRailResponse,
    Case,
    Suite,
    Section,
    Project,
    Plan,
    PlanEntry,
    Run,
    Test,
    Result,
    Milestone,
    User,
    Status,
    Priority,
    AddCasePayload,
    UpdateCasePayload,
    AddPlanPayload,
    AddPlanEntryPayload,
    AddRunPayload,
    AddResultPayload,
    AddResultsForCasesPayload,
    AddResultForCasePayload,
} from './types.js';
